projects:
  cardspacks:
    schemaPath: amplify/backend/api/cardspacks/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: null
        maxDepth: 8
extensions:
  amplify:
    version: 3
