/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://nhhvgwzzgrbbnakway47crydfq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zmgqcgce5fhy5loxjqknwhy5jq",
    "aws_cognito_identity_pool_id": "eu-west-2:00327961-7c50-467d-8e04-d82e29ed8cba",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_9ILT9G770",
    "aws_user_pools_web_client_id": "1lmjh7nqv6qfsvd9i9glfse97m",
    "oauth": {}
};


export default awsmobile;
